// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}
