// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddUser(arg1:string):Promise<void>;

export function DeleteUser(arg1:number,arg2:string):Promise<void>;

export function GetUsers():Promise<Array<main.User>>;

export function UpdateUser(arg1:number):Promise<void>;
